### ISSUE TITLE
Antikode

### ISSUE THREAD

**Issue by masitings** [jazuly/AntiKode#1]
Pagi mas,
Saya cari ini gak ada db seeder atau db yang bs saya taruh di local sy sebagai acuan kah ?

**Comment by jazuly** [comment]
oh iya tidak ada seeder nya mas..
saya pikir ini mau sekalian di coba API nya makanya tidak saya bikin seeder..
untuk generate tablenya bisa via `php artisan migrate` mas..
saat tablenya sudah kebentuk, nanti bisa di coba hit API nya..
saya sudah provide postman collectionnya..

**Comment by jazuly** [comment]
tapin sudah saya tambahkan juga mas kalau tetep butuh https://github.com/jazuly/AntiKode/tree/master/database/schema
